application: gosched 
version: 1
runtime: go
api_version: go1

handlers:
- url: /partials
  static_dir: partials

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: _go_app
