application: csgosched 
version: 1
runtime: go
api_version: go1

handlers:
- url: /images
  static_dir: images

- url: /README.md
  static_files: README.md
  upload: README.md

- url: /partials
  static_dir: partials

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /gosched/.*
  script: _go_app
  login: required

- url: /.*
  script: _go_app

